#!/bin/sh

# Exit immediately if any command exits with a non-zero status.
set -e

if [ $# -lt 1 ]; then
  echo "$0: No module_key supplied - please run 'docker compose exec terraform open <module_key>' to open a shell in the relevant exercise directory."
  exit 2
elif [ $# -eq 1 ]; then
  SW_MODULE_KEY=$1
elif [ $# -gt 1 ]; then
  echo "$0: too many arguments"; exit 2
fi

# Read the attendance id from the file `attendance_id`
TF_VAR_attendance_id=$(cat ./attendance_id)

# Check if the attendance id is still the default, and if so exit with an appropriate error message
if [ $TF_VAR_attendance_id = "your_attendance_id_here" ];
then
    echo "Could not find a valid attendance id in attendance_id file. Please replace the file contents with your attendance id and try again."
    exit 1
fi

# Export the attendance id as an environment variable so that terraform can use it
export TF_VAR_attendance_id

# Change to the relevant exercise directory
cd "exercises/$SW_MODULE_KEY"

# Leave the shell open to further commands
/bin/sh
