#!/bin/sh

# Exit immediately if any command exits with a non-zero status.
set -e

# Read the attendance id from the file `attendance_id`
TF_VAR_attendance_id=$(cat ./attendance_id)

# Check if the attendance id is still the default, and if so exit with an appropriate error message
if [ $TF_VAR_attendance_id = "your_attendance_id_here" ];
then
    echo "Could not find a valid attendance id in attendance_id file. Please replace the file contents with your attendance id and try again."
    exit 1
fi

# Export the attendance id as an environment variable so that terraform can use it
export TF_VAR_attendance_id

# Read the module key from the file /root/.sw_module_key
SW_MODULE_KEY = $(cat /root/.sw_module_key)

# If the module key was manually supplied, and we don't have SW_MODULE_KEY set, then use the manual one.
if
    [ -n $1 ] && [ -z $SW_MODULE_KEY ];
then
    SW_MODULE_KEY=$1
# If both are set, use the manual one, but output a warning if they are different,
elif
    [ -n $1 ] && [ -n $SW_MODULE_KEY ];
then
    if [ $1 != $SW_MODULE_KEY ];
    then
        echo "Warning: module_key supplied manually ($1) does not match the one found using the attendance_id ($SW_MODULE_KEY). Using the manually supplied one."
    fi
    SW_MODULE_KEY=$1
# If neither are set, error
elif
    [ -z $1 ] && [ -z $SW_MODULE_KEY ];
then
    echo "No module_key supplied, and could not find one based on attendance ID - please run 'docker compose exec terraform setup <module_key>' to open a shell in the relevant exercise directory."
    exit 1
fi

# Change to the relevant exercise directory
cd "exercises/$SW_MODULE_KEY"

# If there is existing state, delete it. Any state that is there should be from a previous session, and so will be obsolete as the AWS account will probably be different, and definitely cleared up.
rm -f terraform.tfstate terraform.tfstate.backup

# Initialise terraform - this can't be in the Dockerfile because the subdirectory we want to init is not known at build time.
terraform init

# Create any initial resources specified by the file "initial_state.tf"
terraform apply -auto-approve

# Leave the shell open to further commands
/bin/sh
