version: "3.7"
volumes:
  aws_credentials:
  session_info:
services:
  sync:
    image: "ghcr.io/skiller-whale/learnersync"
    environment:
      SERVER_URL: "https://train.skillerwhale.com/"
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: "/app/exercises"
      ATTENDANCE_ID_FILE: "/app/sync/attendance_id"
      WATCHED_EXTS: "tf"
      IGNORE_DIRS: ".git .terraform"
    volumes:
      - ./exercises:/app/exercises:ro
      - ./attendance_id:/app/sync/attendance_id:ro
    depends_on:
      aws_credentials:
        condition: service_completed_successfully
  terraform:
    build: ./terraform_service
    volumes:
      - ./exercises:/app/exercises
      - ./attendance_id:/app/attendance_id:ro
      - aws_credentials:/root/.aws:ro
      - session_info:/app/.session_info:ro
    depends_on:
      aws_credentials:
        condition: service_completed_successfully
    stop_signal: SIGKILL
  aws:
    image: amazon/aws-cli
    profiles: ["aws-cli"] # Only run this when targetting explicitly
    volumes:
      - aws_credentials:/root/.aws:ro
  aws-cli:
    image: amazon/aws-cli
    entrypoint: ["/bin/bash"] # We may want to expand this into its own dockerfile in order to prepopulate AMI ids using CLI commands.
    profiles: ["aws-cli-interactive"] # Only run this when targetting explicitly
    volumes:
      - aws_credentials:/root/.aws:ro
  aws_credentials:
    build: ./aws_credential_service
    volumes:
      - ./attendance_id:/app/attendance_id:ro
      - aws_credentials:/root/.aws
      - session_info:/root/.session_info
